In [1]:
import pandas as pd 
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option("display.max_columns", None)

In [2]:
df = pd.read_csv("../data/train.csv")

df["date"] = pd.to_datetime(df["date"])

df.head()

        date  store  item  sales
0 2013-01-01      1     1     13
1 2013-01-02      1     1     11
2 2013-01-03      1     1     14
3 2013-01-04      1     1     13
4 2013-01-05      1     1     10

In [3]:
df = df.sort_values(
    by=["store", "item", "date"]
)

df.head()

        date  store  item  sales
0 2013-01-01      1     1     13
1 2013-01-02      1     1     11
2 2013-01-03      1     1     14
3 2013-01-04      1     1     13
4 2013-01-05      1     1     10

In [4]:
df["year"] = df["date"].dt.year

df["month"] = df["date"].dt.month

df["quarter"] = df["date"].dt.quarter

df["day"] = df["date"].dt.day

df["day_of_week"] = df["date"].dt.dayofweek

df["day_of_year"] = df["date"].dt.dayofyear

df["week_of_year"] = df["date"].dt.isocalendar().week.astype(int)

df.head()

,date,store,item,sales,year,month,quarter,day,day_of_week,day_of_year,week_of_year
0,2013-01-01,1,1,13,2013,1,1,1,1,1,1
1,2013-01-02,1,1,11,2013,1,1,2,2,2,1
2,2013-01-03,1,1,14,2013,1,1,3,3,3,1
3,2013-01-04,1,1,13,2013,1,1,4,4,4,1
4,2013-01-05,1,1,10,2013,1,1,5,5,5,1

In [5]:
df["is_weekend"] = np.where(
    df["day_of_week"] >= 5,
    1,
    0
)

df[["date", "day_of_week", "is_weekend"]].head()

        date  day_of_week  is_weekend
0 2013-01-01            1           0
1 2013-01-02            2           0
2 2013-01-03            3           0
3 2013-01-04            4           0
4 2013-01-05            5           1

In [6]:
df["lag_7"] = (
    df.groupby(
        ["store", "item"]
    )["sales"]
    .shift(7)
)

In [7]:
df["lag_14"] = (
    df.groupby(
        ["store", "item"]
    )["sales"]
    .shift(14)
)

In [8]:
df["lag_30"] = (
    df.groupby(
        ["store", "item"]
    )["sales"]
    .shift(30)
)

In [9]:
df["lag_90"] = (
    df.groupby(
        ["store", "item"]
    )["sales"]
    .shift(90)
)

In [10]:
df[
    [
        "date",
        "store",
        "item",
        "sales",
        "lag_7",
        "lag_14"
    ]
].head(20)

         date  store  item  sales  lag_7  lag_14
0  2013-01-01      1     1     13    NaN     NaN
1  2013-01-02      1     1     11    NaN     NaN
2  2013-01-03      1     1     14    NaN     NaN
3  2013-01-04      1     1     13    NaN     NaN
4  2013-01-05      1     1     10    NaN     NaN
5  2013-01-06      1     1     12    NaN     NaN
6  2013-01-07      1     1     10    NaN     NaN
7  2013-01-08      1     1      9   13.0     NaN
8  2013-01-09      1     1     12   11.0     NaN
9  2013-01-10      1     1      9   14.0     NaN
10 2013-01-11      1     1      9   13.0     NaN
11 2013-01-12      1     1      7   10.0     NaN
12 2013-01-13      1     1     10   12.0     NaN
13 2013-01-14      1     1     12   10.0     NaN
14 2013-01-15      1     1      5    9.0    13.0
15 2013-01-16      1     1      7   12.0    11.0
16 2013-01-17      1     1     16    9.0    14.0
17 2013-01-18      1     1      7    9.0    13.0
18 2013-01-19      1     1     18    7.0    10.0
19 2013-01-20      1     1     15   10.0    12.0

In [11]:
df["rolling_mean_7"] = (
    df.groupby(
        ["store", "item"]
    )["sales"]
    .transform(
        lambda x: x.shift(1).rolling(7).mean()
    )
)

In [12]:
df["rolling_mean_30"] = (
    df.groupby(
        ["store", "item"]
    )["sales"]
    .transform(
        lambda x: x.shift(1).rolling(30).mean()
    )
)

In [13]:
df["rolling_std_7"] = (
    df.groupby(
        ["store", "item"]
    )["sales"]
    .transform(
        lambda x: x.shift(1).rolling(7).std()
    )
)

In [14]:
df["rolling_std_30"] = (
    df.groupby(
        ["store", "item"]
    )["sales"]
    .transform(
        lambda x: x.shift(1).rolling(30).std()
    )
)

In [15]:
df.isnull().sum()

date                   0
store                  0
item                   0
sales                  0
year                   0
month                  0
quarter                0
day                    0
day_of_week            0
day_of_year            0
week_of_year           0
is_weekend             0
lag_7               3500
lag_14              7000
lag_30             15000
lag_90             45000
rolling_mean_7      3500
rolling_mean_30    15000
rolling_std_7       3500
rolling_std_30     15000
dtype: int64

In [16]:
df = df.dropna()

df.shape

(868000, 20)

In [17]:
df.head()

,date,store,item,sales,year,month,quarter,day,day_of_week,day_of_year,week_of_year,is_weekend,lag_7,lag_14,lag_30,lag_90,rolling_mean_7,rolling_mean_30,rolling_std_7,rolling_std_30
90,2013-04-01,1,1,11,2013,4,2,1,0,91,14,0,13.0,11.0,13.0,13.0,15.571429,15.400000,3.359422,3.596934
91,2013-04-02,1,1,19,2013,4,2,2,1,92,14,0,16.0,19.0,20.0,11.0,15.285714,15.333333,3.683942,3.660915
92,2013-04-03,1,1,24,2013,4,2,3,2,93,14,0,11.0,14.0,14.0,14.0,15.714286,15.300000,3.946065,3.621297
93,2013-04-04,1,1,18,2013,4,2,4,3,94,14,0,13.0,17.0,13.0,13.0,17.571429,15.633333,4.391550,3.943422
94,2013-04-05,1,1,19,2013,4,2,5,4,95,14,0,17.0,21.0,17.0,10.0,18.285714,15.800000,3.903600,3.933937

In [18]:
df.to_csv(
    "../processed_data/forecasting_features.csv",
    index=False
)

In [21]:
saved_df = pd.read_csv(
    "../processed_data/forecasting_features.csv"
)

print(saved_df.head())

         date  store  item  sales  year  month  quarter  day  day_of_week  \
0  2013-04-01      1     1     11  2013      4        2    1            0
1  2013-04-02      1     1     19  2013      4        2    2            1
2  2013-04-03      1     1     24  2013      4        2    3            2
3  2013-04-04      1     1     18  2013      4        2    4            3
4  2013-04-05      1     1     19  2013      4        2    5            4

   day_of_year  week_of_year  is_weekend  lag_7  lag_14  lag_30  lag_90  \
0           91            14           0   13.0    11.0    13.0    13.0
1           92            14           0   16.0    19.0    20.0    11.0
2           93            14           0   11.0    14.0    14.0    14.0
3           94            14           0   13.0    17.0    13.0    13.0
4           95            14           0   17.0    21.0    17.0    10.0

   rolling_mean_7  rolling_mean_30  rolling_std_7  rolling_std_30
0       15.571429        15.400000       3.359422        3.596934
1       15.285714        15.333333       3.683942        3.660915
2       15.714286        15.300000       3.946065        3.621297
3       17.571429        15.633333       4.391550        3.943422
4       18.285714        15.800000       3.903600        3.933937